<?php

namespace MaConsoBundle\Repository;

/**
 * franceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class franceRepository extends \Doctrine\ORM\EntityRepository
{
}
