<?php

namespace AppBundle\Repository;

/**
 * ChinoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChinoisRepository extends \Doctrine\ORM\EntityRepository
{
}
