<?php

namespace AppBundle\Repository;

/**
 * GestesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestesRepository extends \Doctrine\ORM\EntityRepository
{
}
