<?php

namespace AppBundle\Repository;

/**
 * proutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proutRepository extends \Doctrine\ORM\EntityRepository
{
}
