# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    FormService:
          class: MaConsoBundle\Service\FormService
          arguments: ['@doctrine.orm.entity_manager', 'formService']
    ConsoService:
              class: MaConsoBundle\Service\ConsoService
              arguments: ['@doctrine.orm.entity_manager', 'consoService']
    StatisticService:
                  class: MaConsoBundle\Service\StatisticService
                  arguments: ['@doctrine.orm.entity_manager', 'statisticService']